// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://veulvgnxunfnkjwzdxxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZldWx2Z254dW5mbmtqd3pkeHh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2MzcyMTMsImV4cCI6MjA4OTIxMzIxM30.5MOfi_ASe18YTrgybGTY4QFVnRX9Y8fDcjBJj6FDQXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});